Update STABLE_BRANCH_CHECKLIST.md
gap-system/gap-distribution pull request #116
Opened 2020-11-13 16:07 UTC by fingolfin

2020-11-13 16:44 UTC, wilfwilson requested changes

2020-11-13 16:44 UTC, wilfwilson commented on DistributionUpdate/STABLE_BRANCH_CHECKLIST.md
> +  - `READE.md`: change the badges at the top to refer to `stable-X.Y`
```suggestion
  - `README.md`: change the badges at the top to refer to `stable-X.Y`
```

2020-11-13 19:20 UTC, fingolfin commented on DistributionUpdate/STABLE_BRANCH_CHECKLIST.md
> +  This tag is then used by `git describe` and ensures that GAP development build carry a suitable version number.
```suggestion
  This tag is then used by `git describe` and ensures that GAP development builds carry a suitable version number.
```

2020-11-13 21:00 UTC, wilfwilson approved these changes

2021-02-16 12:18 UTC, fingolfin commented
@alex-konovalov can we merge this?

2021-02-16 13:09 UTC, alex-konovalov approved these changes

2021-02-16 13:09 UTC, merged